env:
  browser: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  semi:
    - error
    - always
settings:
  react:
    version: "detect"
